title: "NUStorage"
theme: jekyll-theme-minimal

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2021S1-CS2103T-T11-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
